#index:
#    path: /
#    controller: App\Controller\DefaultController::index
oc_advert_index:
    path:   /advert
    controller: App\Controller\AdvertController::index

oc_advert_view:
    path:   /advert/view/{id}
    controller: App\Controller\AdvertController::view

oc_advert_add:
    path:   /advert/add
    controller: App\Controller\AdvertController::add

oc_advert_menu:
    path:   /advert/menu
    controller: App\Controller\AdvertController::menuAction

oc_advert_edit:
    path:   /advert/edit
    controller: App\Controller\AdvertController::edit

oc_advert_delete:
    path:   /advert/delete
    controller: App\Controller\AdvertController::delete
